### ISSUE TITLE
思源主题列表没对齐

### ISSUE THREAD

**Issue by roverway** [ihyw/Watermelon#1]
![image](https://user-images.githubusercontent.com/657850/104939419-5a2cbc80-59eb-11eb-9e3c-18c51dc1fc87.png)

如上图，有序列表下级是无需列表，和有序列表下级是有序列表时候，前后两级列表的左侧边距是不一样的。看着有点不协调。
而且004版本，下级列表切换有序或者无序的时候列表会乱掉，用daylight就不会。

大佬可以看看是为啥

**Comment by ihyw** [comment]
啊，非常感谢您的issue！我刚刚看见邮箱就来找问题了，目前问题已经定位和修复，等待PR后烦请更新一下
1.边距这个确实是考虑不周，没有来调这个场景，仓促就上线了，然后后面就没有来测试
2.下级列表切换混乱是因为我的选择器少了个>，在无序列表下去应用了有序列表的样式
3.顺带处理了一下之前用伪元素的遗留问题，会在删除列表后留下列表的标记
哈哈回复不太及时，抱歉，昨晚就睡了！

**Comment by roverway** [comment]
感谢大佬的众多主题，这个不着急的。

**Comment by ihyw** [comment]
老哥客气啦，主题已经更新，可以去试试看还有没有问题，其实我用的时候有个偶发的问题，不过可以等以后再考虑修改

**Comment by roverway** [comment]
感谢老哥，新主题用上了，很不错，没发现啥问题；
要说改进的话，多级列表序号不知道是否可以改成 1，1.1， 1.1.1 这种？目前已有主题支持这种序号，但貌似同时思源笔记左侧显示的各种块图标会发生错位，不知道是不是一个不好搞的问题。

**Comment by ihyw** [comment]
有序列表的改进有弄过，但是考虑到CSS的计数函数在没有JS来动态修改padding宽度的情况下会使得光标永远都在一个位置，有点败体验，就没有加入。因为毕竟只能用伪元素来实现，所以无法去变动光标。

**Comment by roverway** [comment]
看来果然是技术上不好搞，那就这样吧，现在已经很不错了，整齐美观。谢谢啦。

**Comment by ihyw** [comment]
哈哈哈，不客气，有问题随时探讨！
