### ISSUE TITLE
有序列表的标识被遮挡了

### ISSUE THREAD

**Issue by MACDfree** [ihyw/Watermelon#2]
默认主题中的展示：

![image](https://user-images.githubusercontent.com/3363410/106856363-4bd3e580-66f9-11eb-82f1-fd0717a81f4f.png)

本主题中的展示：

![image](https://user-images.githubusercontent.com/3363410/106856452-70c85880-66f9-11eb-9c6c-efb4804b75a7.png)

**Comment by ihyw** [comment]
您好，感谢您的反馈， 我已经处理了这个问题，不过我把原来放在最内层的列表块处理在了外层，等之后更新了应该就没有这个问题了！

**Comment by ihyw** [comment]
老哥，目前思源以及更新至v0.8.5，更新软件后更新一下主题再看看有没有啥问题，随时联系~

**Comment by MACDfree** [comment]
![image](https://user-images.githubusercontent.com/3363410/106916855-9f1e5600-6742-11eb-84df-fca261f5661a.png)

这块图标没有显示全。并且，这个图标是可以选中拖拽修改列表顺序的，所以还有需要的。

**Comment by ihyw** [comment]
大意了，明天接着改！

**Comment by ihyw** [comment]
![image](https://user-images.githubusercontent.com/74618439/106925916-7ea6c980-674b-11eb-963c-44456a360e4a.png)
问题已经在本地定位处理，等下个版本更新后请老哥再看看，感谢！

**Comment by ihyw** [comment]
![image](https://user-images.githubusercontent.com/74618439/106927647-5324de80-674d-11eb-9739-1313aaf77e0a.png)
已经完全对齐，拖动也是ok的了

**Comment by MACDfree** [comment]
测试了一下，我这边没问题了。谢谢👍👍👍
