### ISSUE TITLE
【建议】标题块和代码块的标识建议不要离这么远

### ISSUE THREAD

**Issue by MACDfree** [ihyw/Watermelon#3]
![image](https://user-images.githubusercontent.com/3363410/106976614-ab7ecf00-6793-11eb-8790-0a1341ca9241.png)

标题和代码块标识建议和段落标识的位置一致。当鼠标从上到下划过的时候感觉比较明显。

只是建议，不改也不影响使用。

**Comment by ihyw** [comment]
哈哈哈我的锅，昨天晚上只写了列表的情况就更了，我今天好好完善一下再更！

**Comment by ihyw** [comment]
老哥，更新过了吗，看看还有没有啥地方需要改

**Comment by MACDfree** [comment]
不好意思，忘记回复了。目前用着没啥问题，蛮养眼的。👍
