### ISSUE TITLE
动态查询块标识位置需要优化下

### ISSUE THREAD

**Issue by MACDfree** [ihyw/Watermelon#4]
好吧，我又来了，发现漏了动态查询块标识的。

![image](https://user-images.githubusercontent.com/3363410/107371924-cf3d6e80-6b1f-11eb-8071-000c2e1f11d6.png)

**Comment by ihyw** [comment]
好家伙，这个给漏了，老哥要是急的话可以先在css文件中做如下修改
![image](https://user-images.githubusercontent.com/74618439/107372476-699db200-6b20-11eb-83bf-63add0b8d307.png)

**Comment by MACDfree** [comment]
嗯嗯，可以了。

**Comment by ihyw** [comment]
应该已经是更新了，那我就先关闭啦哈哈
